#!/usr/bin/with-contenv /bin/sh

INSTALLED_BASE_DIR=${WILDFLY_HOME}/standalone.OEM

if [ -d ${WILDFLY_RUNTIME_BASE_DIR} ]; then
  exit
fi

mkdir ${WILDFLY_RUNTIME_BASE_DIR}
tar -C ${INSTALLED_BASE_DIR} -cf - . | tar -C ${WILDFLY_RUNTIME_BASE_DIR} -xf -
chown -R ${WILDFLY_USER}:${WILDFLY_USER} ${WILDFLY_RUNTIME_BASE_DIR}
