#!/usr/bin/with-contenv /bin/sh

intf=${WILDFLY_BIND_INTERFACE:-eth0}

if [ "$intf" != "any" ]; then
  addr=$(ip address scope global dev ${intf} \
            | grep "inet" \
            | awk '{print $2}' \
            | cut -f1 -d'/')
else
  addr=0.0.0.0
fi

echo $addr > ${WILDFLY_BIND_ADDRESS}
chown ${WILDFLY_USER}:${WILDFLY_USER} ${WILDFLY_BIND_ADDRESS}
echo "bind address is $(cat ${WILDFLY_BIND_ADDRESS})"

