#!/usr/bin/with-contenv /bin/sh

function intf2addr() {
  intf=$1
  if [ "$intf" == "any" ]; then
    addr=0.0.0.0
  elif [ "$intf" == "lo" ]; then
    addr=127.0.0.1
  elif ip link list dev "$intf" >/dev/null 2>&1; then
    addr=$(ip address list scope global dev ${intf} \
              | grep "inet" \
              | awk '{print $2}' \
              | cut -f1 -d'/')
  else
    addr=$(ip route list $intf | awk '{print $NF}')
  fi

  if [ -z "$addr" ]; then
    echo "WARNING: cannot determine interface address for '$intf'" >&2
    echo "WARNING: binding to all interfaces as a fallback" >&2
    addr=0.0.0.0
  fi

  echo $addr
}

bind_addr=$(intf2addr ${WILDFLY_BIND_INTERFACE:-eth0})
echo $bind_addr > ${WILDFLY_BIND_ADDRESS}
chown ${WILDFLY_USER}:${WILDFLY_USER} ${WILDFLY_BIND_ADDRESS}
echo "bind address is $(cat ${WILDFLY_BIND_ADDRESS})"

if [ -z "${WILDFLY_MGMT_BIND_INTERFACE}" ]; then
  echo $bind_addr > ${WILDFLY_MGMT_BIND_ADDRESS}
  chown ${WILDFLY_USER}:${WILDFLY_USER} ${WILDFLY_MGMT_BIND_ADDRESS}
else
  mgmt_bind_addr=$(intf2addr "${WILDFLY_MGMT_BIND_INTERFACE}")
  echo $mgmt_bind_addr > ${WILDFLY_MGMT_BIND_ADDRESS}
  chown ${WILDFLY_USER}:${WILDFLY_USER} ${WILDFLY_MGMT_BIND_ADDRESS}
  echo "management bind address is $(cat ${WILDFLY_MGMT_BIND_ADDRESS})"
fi  
