#!/usr/bin/with-contenv /bin/sh

CONFIG_LOCK=/var/run/wildfly-config.lock
CONFIG_DIR=${WILDFLY_CONFIG_DIR:-/etc/wildfly/config.d}
ME="[wildfly/config.d]"
CLI=/apps/wildfly/bin/jboss-cli.sh

if [ -f "$CONFIG_LOCK" ]; then
  echo "$ME configuration has already been applied"
  exit
fi

WILDFLY_HA=$(echo "$WILDFLY_HA" | tr [A-Z] [a-z] | sed 's/^yes$/true/')
echo "$ME HA configuration=${WILDFLY_HA}"

if [ "$WILDFLY_HA" == "true" ]; then
  wildfly_config=${WILDFLY_RUNTIME_BASE_DIR}/configuration
  cp ${wildfly_config}/standalone-ha.xml ${wildfly_config}/standalone.xml
  chown ${WILDFLY_USER}:${WILDFLY_USER} ${wildfly_config}/standalone.xml
fi

if [ ! -d "${CONFIG_DIR}" ]; then
  echo "${CONFIG_DIR}: not found" >&2
  exit 1
fi

CONFIG_BASE=$(dirname $CONFIG_DIR)
for file in $(ls $CONFIG_BASE); do
  if [ -f $file ]; then
    echo "$ME installing file ${CONFIG_BASE}/${file}"
    cp ${CONFIG_BASE}/${file} ${WILDFLY_RUNTIME_BASE_DIR}/configuration/
  fi
done

echo "$ME applying configuration in ${CONFIG_DIR}"

CLI_SCRIPT=$(mktemp)
echo "embed-server" > $CLI_SCRIPT

count=0
for file in $(ls "$CONFIG_DIR"); do
  snippet="${CONFIG_DIR}/${file}"

  if echo $snippet | grep "^.*\.ha$" 2>&1 1>/dev/null; then
    if [ "$WILDFLY_HA" != "true" ]; then
      echo "$ME omitting HA-specific configuration $snippet"
      continue
    fi
  fi

  if [ -f "$snippet" ]; then
    echo "echo $ME $file" >> $CLI_SCRIPT  
    echo "run-batch --file=$snippet" >> $CLI_SCRIPT
    count=$(expr $count + 1)
  fi
done

chown $WILDFLY_USER $CLI_SCRIPT
if [ $count -ne 0 ]; then
  s6-setuidgid $WILDFLY_USER $CLI --file="$CLI_SCRIPT"
fi

rm $CLI_SCRIPT
touch $CONFIG_LOCK
