#!/usr/bin/with-contenv /bin/sh

CONFIG_LOCK=/var/run/wildfly-config.lock
CONFIG_DIR=${WILDFLY_CONFIG_DIR:-/etc/wildfly/config.d}
ME="[wildfly/config.d]"
CLI=/apps/wildfly/bin/jboss-cli.sh

if [ -f "$CONFIG_LOCK" ]; then
  echo "configuration has already been applied"
  exit
fi

if [ ! -d "${CONFIG_DIR}" ]; then
  echo "${CONFIG_DIR}: not found" >&2
  exit 1
fi

echo "applying configuration in ${CONFIG_DIR}"

CLI_SCRIPT=$(mktemp)
echo "embed-server" > $CLI_SCRIPT

count=0
for file in $(ls "$CONFIG_DIR"); do
  snippet="${CONFIG_DIR}/${file}"
  if [ -f "$snippet" ]; then
    echo "echo $ME $file" >> $CLI_SCRIPT  
    echo "run-batch --file=$snippet" >> $CLI_SCRIPT
    count=$(expr $count + 1)
  fi
done

if [ $count -ne 0 ]; then
  $CLI --file="$CLI_SCRIPT"
fi

rm $CLI_SCRIPT
touch $CONFIG_LOCK
